---
title: "assignment3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Student:Shengqian Zou  Student ID:z5203970

Q1
```{r, message=FALSE, warning=FALSE}
Sigma <- matrix(c(209, -55, -12, 0, -55, 363, -10, 13, -12, -10, 52, -52, 0, 13, -52, 169), 4, 4)
n<-30
p<-4
Sigma_H0<-diag(diag(Sigma))
L0<-((2*pi)^(-n*p/2))*det(Sigma_H0)^(-n/2)*exp(-1/2*sum(diag(solve(Sigma_H0)%*%(n*Sigma))))
L1<-((2*pi)^(-n*p/2))*(n^(n*p/2))*(det(n*Sigma)^(-n/2))*exp(-1/2*n*p)
Lambda<-L0/L1
Statistics = -2 * log(L0/L1) #H0 chisq(df)~test statistics
df <- p*(p+1)/2-p
# critical value, if test statistic value > critical value, then reject H0
qchisq(0.95,df) # < test statistic value,reject H0
(ans_e_chisq <- Statistics)
(ans_e_df <-df)
(ans_e_pval <- pchisq(Statistics,df, lower.tail = FALSE))
```

Q2 a_i
```{r, message=FALSE, warning=FALSE}
Sigma <- matrix(c(1, 0.8, 0.2, 0.8, 0.9, 0.4, 0.2, 0.4, 1.9), 3, 3)
Mu <-  matrix(c(-0.1, -0.9, -0.2, 0.3, -0.4, -0.6, -1.6, 0, 0.6), 3, 3, byrow=TRUE, dimnames = list(c("Normal", "Anxiety", "Obsession"), c("A", "B", "C")))

ans_a_i_N <- function(A,B,C) {
  coefficient <- Mu[1,]%*%solve(Sigma)
  intercept <- -1/2*Mu[1,]%*%solve(Sigma)%*%Mu[1,]
  output <- coefficient%*%c(A,B,C)+intercept+log(1/3)
  return (output)
}

ans_a_i_A <- function(A,B,C) {
  coefficient<-Mu[2,]%*%solve(Sigma)
  intercept<- -1/2*Mu[2,]%*%solve(Sigma)%*%Mu[2,]
  output<-coefficient%*%c(A,B,C)+intercept+log(1/3)
  
  return (output)
}
ans_a_i_O <- function(A,B,C) {
  coefficient <- Mu[3,]%*%solve(Sigma)
  intercept <- -1/2*Mu[3,]%*%solve(Sigma)%*%Mu[3,]
  output <- coefficient%*%c(A,B,C)+intercept+log(1/3)
  return (output)
}
```


Q2 a_ii
```{r, message=FALSE, warning=FALSE}
#A=−0.5 , B=−0.4, C=−0.4 c(-0.5, -0.4, -0.4)
ans_a_i_N(-0.5, -0.4, -0.4)
ans_a_i_A(-0.5, -0.4, -0.4)
ans_a_i_O(-0.5, -0.4, -0.4)
P = exp(-2.553894) + exp(-2.070091) +exp(-4.702368)
ans_ai_N = exp(-2.553894)/P
ans_ai_A = exp(-2.070091)/P
ans_ai_O = exp(-4.702368)/P
(ans_a_ii = c(ans_ai_N,ans_ai_A,ans_ai_O))
```


Q2 a_iii
```{r, message=FALSE, warning=FALSE}
ans_a_iii_N <- function(A,B,C) {
  coefficient <- Mu[1,]%*%solve(Sigma)
  intercept <- -1/2*Mu[1,]%*%solve(Sigma)%*%Mu[1,]
  output <- coefficient%*%c(A,B,C)+intercept+log(0.4)
  return (output)
}

ans_a_iii_A <- function(A,B,C) {
  coefficient<-Mu[2,]%*%solve(Sigma)
  intercept<- -1/2*Mu[2,]%*%solve(Sigma)%*%Mu[2,]
  output<-coefficient%*%c(A,B,C)+intercept+log(0.3)
  
  return (output)
}
ans_a_iii_O <- function(A,B,C) {
  coefficient <- Mu[3,]%*%solve(Sigma)
  intercept <- -1/2*Mu[3,]%*%solve(Sigma)%*%Mu[3,]
  output <- coefficient%*%c(A,B,C)+intercept+log(0.3)
  return (output)
}
ans_a_iii_N(-0.5, -0.4, -0.4)
ans_a_iii_A(-0.5, -0.4, -0.4)
ans_a_iii_O(-0.5, -0.4, -0.4)

P_iii = exp(-2.371572) + exp(-2.175452) +exp(-4.807729)
ans_aiii_N = exp(-2.371572)/P_iii
ans_aiii_A = exp(-2.175452)/P_iii
ans_aiii_O = exp(-4.807729)/P_iii
(ans_a_ii = c(ans_aiii_N,ans_aiii_A,ans_aiii_O))

```

Q2 a_iv
```{r, message=FALSE, warning=FALSE}
Delta<-sqrt((Mu[2,]-Mu[3,])%*%solve(Sigma)%*%(Mu[2,]-Mu[3,]))
(ans_a_iv_pAO <-pnorm(-Delta/2))
Delta_OA<-sqrt((Mu[3,]-Mu[2,])%*%solve(Sigma)%*%(Mu[3,]-Mu[2,]))
(ans_a_iv_pOA <-pnorm(-Delta_OA/2))
```

Q2 b_i
```{r, message=FALSE, warning=FALSE}
G <- c('Normal', 'Anxiety', 'Obsession', 'Normal', 'Anxiety', 'Normal', 'Normal', 'Obsession', 'Obsession', 'Normal', 'Anxiety', 'Obsession', 'Normal', 'Obsession', 'Anxiety', 'Normal', 'Normal', 'Obsession', 'Obsession', 'Normal', 'Normal', 'Anxiety', 'Anxiety', 'Normal', 'Obsession', 'Normal', 'Anxiety', 'Normal', 'Normal', 'Anxiety', 'Normal', 'Obsession', 'Obsession', 'Anxiety', 'Anxiety', 'Normal')
X <- matrix(c(0.5, -0.4, 1, -0.8, -1.8, 1.7, -1, 0.2, 2.3, 1, -0.7, -0.3, 0.1, -0.8, 1.9, -0.5, -1.4, -1.6, -0.1, -0.8, -0.3, -2.2, 0.1, -1.5, -2.1, 0.5, 0.5, -0.2, -1.2, -1.6, 0.6, -1.1, -0.5, 0.2, 1.2, -0.9, 1.4, -0.4, -2.1, -2.7, -1.4, 0, -1.1, -0.7, -0.6, -1.1, -2, -1.4, 1.8, 0.7, -2.1, -2.5, -1, 0.5, -1.5, -0.4, 1.9, 0.5, -0.7, -0.7, 0.6, -0.5, -1, 1.8, 1.9, -1.3, -0.5, -2.2, 1.5, -0.9, -0.9, 0, -1.1, -0.3, -1.1, 0.7, -1.2, -2.6, 0, -0.5, -1, 0.2, -0.7, -2.6, 0.5, -0.3, -0.6, 0.3, 0.3, -0.7, -0.6, -0.9, -1, 0.4, 0.7, 0.4, -3.7, -1.7, 1.5, 2.6, 1.1, -0.2, 0.1, -1.2, -0.2, -2.4, -3.5, -2), 36, 3, byrow=TRUE, dimnames=list(NULL, c("A","B","C")))
neurotic <- cbind(data.frame(Diagnosis=G), X)
write.csv(neurotic, "neurotic.csv", row.names=FALSE)

library(MASS)
reframe <- data.frame(A=-0.5, B=-0.4, C=-0.4)
# Using LDA:
(neuroticlda <- lda(Diagnosis~., neurotic, prior=c(1,1,1)/3))
predict(neuroticlda, newdata=reframe)
```

Q2 b_ii
```{r, message=FALSE, warning=FALSE}
table(neurotic$Diagnosis,predict(neuroticlda)$class)
(ans_b_ii <- matrix(c(12,4,0,3,6,1,0,0,10),3,3,byrow=TRUE)) # 3*3
```

Q2 b_iii
```{r, message=FALSE, warning=FALSE}
library(heplots)
library(dplyr)

neurotic.mlm <-lm(as.matrix(select(neurotic,-Diagnosis))~Diagnosis,
                  data=neurotic)
boxM(neurotic.mlm)
```

Q2 c
```{r, message=FALSE, warning=FALSE}
library(e1071)
set.seed(1)

summary(tuned.svm <- tune.svm(factor(Diagnosis)~.,data=neurotic,kernel="radial", gamma = 10^(-1:1), cost = 10^(-1:1)))
#Choose the one with the lowest error rate, that is, when ganma is equal to 0.1 and cost is equal to 10
#In addition, test other values to compare to see if this is the highest score
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=0.1, cost = 1, cross=5)$tot.accuracy#61.11111
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=0.1, cost = 10, cross=5)$tot.accuracy#63.88889
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=0.5, cost = 10, cross=5)$tot.accuracy#52.77778
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=1, cost = 10, cross=5)$tot.accuracy#55.55556
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=5, cost = 10, cross=5)$tot.accuracy#52.77778
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=10, cost = 10, cross=5)$tot.accuracy#41.66667
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=0.1, cost = 30, cross=5)$tot.accuracy#58.33333
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=2, cost = 20, cross=5)$tot.accuracy#63.88889
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=3, cost = 15, cross=5)$tot.accuracy#50
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=2, cost = 5, cross=5)$tot.accuracy#50
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=2, cost = 50, cross=5)$tot.accuracy#61.11111
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=9, cost = 50, cross=5)$tot.accuracy#38.88889
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=3, cost = 70, cross=5)$tot.accuracy#47.22222
svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=5, cost = 20, cross=5)$tot.accuracy#50
#Choose the ganma=0.1, cost=10
summary(SVM<- svm(factor(Diagnosis)~.,data=neurotic, kernel="radial", gamma=0.1, cost = 10, cross=5))

reframe <- data.frame(A=-0.5, B=-0.4, C=-0.4)
(obpred <- predict(SVM, reframe))
```

Q3 a_i
```{r, message=FALSE, warning=FALSE}
library(psych)
library(dplyr)

X <- matrix(c(-0.47,-0.13,-0.1,1.31,0.92,-0.7,0.18,-0.49,0.06,-0.19,0.01,-0.33,-0.99,-0.38,1.4,0.34,-0.88,-0.65,-0.06,0.24,0.47,1.34,1.61,-2.46,-0.07,0.77,0.15,-1.08,-0.32,-2.37,1.52,0.89,-1.07,0.26,-3.08,0,1.1,0.26,1.64,1.02,1.19,-1.12,0.21,3.33,0.16,-0.3,0.25,0.58,0.4,-0.25,1.73,0.15,-0.52,0.61,-0.25,0.15,0.05,-0.43,-0.49,1.58,0.11,-1.26,-0.37,-0.25,-0.12,-0.6,0.38,-0.27,-0.65,0.16,-0.39,-0.77,0.76,-0.01,1.73,1.02,1.54,-0.68,0.03,2.12,-0.12,-1.67,0.35,-2.27,0.37,0.44,-0.52,-0.2,-3.4,-0.08,-0.51,-0.53,-0.61,0.91,1.4,-1.59,-0.21,-1.51,0.18,-1.46,-0.58,-2,1.44,1.47,1.12,-0.01,-1.83,-0.23,-0.03,0.14,-0.19,0.42,-1.4,-1.01,-0.04,0.29,-0.66,-0.17,-0.12,-1.04,2.96,2.11,-4.07,0.13,0.19,-0.41,-0.02,-0.06,-1.12,-0.66,-0.56,-0.52,0,-1.11,0.6,0.89,0.18,1.28,1.19,1.36,-0.98,0.36,2.21,0.04,0.29,-0.46,0.32,0.6,0.05,-0.13,0.03,0.58,-0.66,0.63,-0.25,0.35,-3.23,-2.03,0.82,0.16,1.75,-0.45,0.38,-0.28,0.52,-1.04,-1.55,1.3,-0.05,1.59,0.2,0.58,-0.24,0.58,0.97,-0.32,1.11,-0.02,1.97,-0.03,-0.38,0.18,-0.62,0.18,0.12,-0.45,0.03,-0.52,-0.16,0.86,0.14,0.66,1.12,1.25,1.38,0.24,1.71,-0.79,-0.5,-0.07,-0.81,2.31,1.93,-1.81,0,-1.55,-0.24,-0.98,0.02,-0.28,1.13,0.64,-0.12,-0.19,-1.24,0.21,0.49,-0.45,1.88,2.41,2.17,-0.62,-0.14,1.36,0.37,-0.51,-0.06,-0.77,-0.35,-1.6,2.28,0,-2.75,-0.68,0.32,0.45,0.72,0.92,1.03,0.36,-0.45,1.88,0.34,0.07,0.16,-0.2,-0.87,-0.73,2.02,-0.01,0.04,-0.06,1.19,0.25,1.04,1.83,-0.79,0.7,0.36,2.73,0.2,-0.15,-0.35,0.24,0.34,0.45,0.68,-0.02,1.3,-0.12,-0.47,0.34,-0.9,2.42,2.06,-0.64,0.17,-0.36,-0.09,0.98,-0.27,1.12,-1.79,-0.3,-1.07,0.09,2.5,0,0.92,0.07,1.22,0.91,0.79,-2.21,0.02,2.21,-0.27,-0.21,0.33,-0.29,-1.16,-0.42,0.07,0.01,-0.45,-0.3,-1.12,0.06,-1.05,0.74,0.33,-0.95,-0.22,-2.49,0.01,-0.38,0.13,-0.32,0.46,-0.42,0.07,-0.46,-1.28,-0.64,-0.73,0.41,0.34,0.46,1.11,-0.33,-0.04,-0.65,0.11,-0.38,0.06,-0.74,0.83,0.06,1.04,0.01,0.02,0.14,-0.18,0.05,-1.1,-1.49,-1.51,2.38,0.06,-0.92,-0.09,0.79,-0.13,1.04,-1.42,-0.97,1.12,0.06,1.55,0.1,-1.83,-0.03,-1.55,2.4,2.86,-3.89,0.14,-4.39,0.72,0.92,0.35,1.05,-1.3,-1.7,2.7,-0.14,1.38,-0.2,-0.12,-0.5,-0.5,2.1,1.14,-2.18,0.07,-0.53,-0.12,-0.32,0.09,-0.38,0.18,-0.03,0.59,-0.12,-0.35,0.1,-0.65,-0.05,-1.66,0.9,-0.02,0.4,0.15,-2.08,0.53,0.73,0.29,1.37,-0.95,-0.58,1.23,-0.1,2.5,0.5,-0.5,-0.02,-0.2,0.29,-0.2,-0.85,-0.07,-1.1,0.4,-0.48,0.4,-0.97,-1.28,-1.44,1.32,0.32,-0.57,0.01,0.94,0.36,1.48,2.05,1.01,-0.98,-0.06,1.4,0.53,0.63,-0.35,0.3,-0.07,-0.75,0.11,-0.09,1.31,0.31,-0.16,0.5,0.02,-1.94,-1.34,0.87,-0.32,-0.32,-0.09,0,-0.2,0.15,-1.68,-0.69,1.41,0.13,-0.07,0.02,0.45,0.27,0.39,0.1,0.25,0.43,-0.13,0.7,-0.96,-1.61,0.47,-2.07,0.24,0.45,0.37,-0.18,-4.4,0.25,-0.08,-0.45,0.68,-2.72,-1.76,0.19,0.07,-0.05,0.04,-0.13,0,0.02,0.85,0.49,0.83,-0.13,1.44,-0.24), nrow=56, ncol=9, byrow=TRUE, dimnames=list(NULL,paste0("X",1:9)))
write.csv(as.data.frame(X), file="X.csv")

(ans_a_i <- factanal(X, 1))
```

Q3 a_ii
```{r, message=FALSE, warning=FALSE}
(ans_a_ii <- factanal(X, 2))
```

Q3 a_iii
```{r, message=FALSE, warning=FALSE}
(ans_a_iii <- factanal(X, 3))
```

Q3 ans_a_iv = 2

Q3 b_i
```{r, message=FALSE, warning=FALSE}
(b_i <- fa(X, 2,fm='ml',rotate='varimax'))
(ans_b_i_f1 <- c(4,5,6))
(ans_b_i_f2 <- c(1,3,8))
```

Q3 b_ii
```{r, message=FALSE, warning=FALSE}
b_i$loadings
Lambda <- matrix(c(0.946, -0.216, 0, 0, 0.901, 0, 0, 0.844, 0, 0.997, 0, -0.687, 0.144, 0, 0.956, -0.106, 0, 0.175), byrow = TRUE,ncol = 2)
Sigma_error <- b_i$uniquenesses
(ans_b_ii = Lambda %*% t(Lambda) + diag(Sigma_error))
```